### ISSUE TITLE
Cannot launch the program

### ISSUE THREAD

**Issue by emyfops** [vantonuk35/Fnf_bot#1]
![Sans titre](https://user-images.githubusercontent.com/46357922/124614327-1c5d0c80-de42-11eb-8f1d-c786987c9493.png)

**Comment by vantonuk35** [comment]
1.what is your display resolution
2.Do you have few displays?

**Comment by emyfops** [comment]
1920x1080

**Comment by vantonuk35** [comment]
Try launch bot few times when it s crashing and put game in windowed mode at center of screen

**Comment by emyfops** [comment]
Damn its working very well, good job mate, you should add in the readme to put the game in window mode in the middle of the screen

**Comment by vantonuk35** [comment]
ok thanks

**Comment by vantonuk35** [comment]
but itsnt work with last level yet

**Comment by emyfops** [comment]
Its working on most mods

**Comment by emyfops** [comment]
In fact the program is literally better than the popular FnfBot by Kade
Here a test i made on a difficult level: https://youtu.be/cmLxKGw4MHE
