### ISSUE TITLE
I found why its not working on all mods

### ISSUE THREAD

**Issue by emyfops** [vantonuk35/Fnf_bot#2]
So i checked the code for few minutes and i saw you were scanning if there is a window named Friday Night Funkin, but some mods name are called Friday Night Funkin Kade Engine, or even custom
A way to fix this is by scanning if the window contain the word " Funkin' "

**Comment by vantonuk35** [comment]
No its about screen scanning. If you have another arrow color, it cant detect it

**Comment by emyfops** [comment]
I checked two different mod, one is working, the other no, and both have the same arrows colors

**Comment by vantonuk35** [comment]
Try to start Last level in original game

**Comment by emyfops** [comment]
Im talking about this piece of code `while ((game_window=FindWindowA(NULL, "Friday Night Funkin'")))`

**Comment by emyfops** [comment]
The program crash on certain mods because of the different window name

**Comment by vantonuk35** [comment]
I will edit it later

**Comment by emyfops** [comment]
No problem
