### ISSUE TITLE
Optimisation idea

### ISSUE THREAD

**Issue by emyfops** [vantonuk35/Fnf_bot#3]
The program is scanning the the of the arrows to send input

My idea is to scan the bottom and and the top, it would we useful for the mods with customs arrows like Tricky, when an arrows appear at the bottom, it will count the time it take for the note to touch the arrows patern to be the most accurate possible.
Footage: [Stress test video](https://cdn.discordapp.com/attachments/811283553114390528/862355377093738556/2021-07-07_11-30-17.mp4)

**Comment by emyfops** [comment]
![bottomtop](https://user-images.githubusercontent.com/46357922/124788618-83002a00-df17-11eb-9e27-d6e2409a089e.png)

**Comment by vantonuk35** [comment]
i dont think that it will work beecause diffrent songs have diffrent bpm

**Comment by emyfops** [comment]
I mean, when the note touch the hitbox of the bottom one, it will count the time in ms of when the note will hit the hitbox up

Do you have any direct method to have contact ?

**Comment by vantonuk35** [comment]
Discord : Vadim Antonuk#7941
